import { render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import App from "./App";

vi.mock("./api/client", () => ({
  getOverview: vi.fn(async () => ({
    generatedAt: "2026-03-14T00:00:00Z",
    gameweeks: [
      {
        id: 1,
        name: "Gameweek 1",
        deadlineTime: "2026-08-15T10:00:00Z",
        averageEntryScore: 57,
        highestScore: 102,
        isCurrent: true,
        isFinished: false,
      },
    ],
    topPlayers: [
      {
        id: 10,
        webName: "Saka",
        firstName: "Bukayo",
        secondName: "Saka",
        teamId: 1,
        teamName: "Arsenal",
        teamShortName: "ARS",
        positionId: 3,
        positionName: "Midfielder",
        nowCost: 105,
        totalPoints: 215,
        form: 7.8,
        selectedByPercent: 35.6,
        pointsPerGame: 6.1,
        goalsScored: 16,
        assists: 12,
        cleanSheets: 10,
        minutes: 2890,
        bonus: 30,
        bps: 620,
        creativity: 980.5,
        influence: 1122.4,
        threat: 901.7,
        ictIndex: 300.4,
        expectedGoals: 14.6,
        expectedAssists: 11.2,
        expectedGoalInvolvements: 25.8,
        expectedGoalsConceded: 22.3,
        cleanSheetsPer90: 0.31,
        starts: 33,
        tackles: 54,
        recoveries: 146,
        defensiveContribution: 88,
        status: "a",
      },
    ],
    fixtures: [
      {
        id: 1,
        code: 111,
        eventId: 1,
        kickoffTime: "2026-08-16T15:30:00Z",
        teamH: 1,
        teamA: 2,
        teamHName: "Arsenal",
        teamAName: "Chelsea",
        teamHShortName: "ARS",
        teamAShortName: "CHE",
        teamHScore: null,
        teamAScore: null,
        finished: false,
        started: false,
      },
    ],
    teams: [],
  })),
  getPlayers: vi.fn(async () => [
    {
      id: 10,
      webName: "Saka",
      firstName: "Bukayo",
      secondName: "Saka",
      teamId: 1,
      teamName: "Arsenal",
      teamShortName: "ARS",
      positionId: 3,
      positionName: "Midfielder",
      nowCost: 105,
      totalPoints: 215,
      form: 7.8,
      selectedByPercent: 35.6,
      pointsPerGame: 6.1,
      goalsScored: 16,
      assists: 12,
      cleanSheets: 10,
      minutes: 2890,
      bonus: 30,
      bps: 620,
      creativity: 980.5,
      influence: 1122.4,
      threat: 901.7,
      ictIndex: 300.4,
      expectedGoals: 14.6,
      expectedAssists: 11.2,
      expectedGoalInvolvements: 25.8,
      expectedGoalsConceded: 22.3,
      cleanSheetsPer90: 0.31,
      starts: 33,
      tackles: 54,
      recoveries: 146,
      defensiveContribution: 88,
      status: "a",
    },
  ]),
  getPlayer: vi.fn(async () => ({
    player: {
      id: 10,
      webName: "Saka",
      firstName: "Bukayo",
      secondName: "Saka",
      teamId: 1,
      teamName: "Arsenal",
      teamShortName: "ARS",
      positionId: 3,
      positionName: "Midfielder",
      nowCost: 105,
      totalPoints: 215,
      form: 7.8,
      selectedByPercent: 35.6,
      pointsPerGame: 6.1,
      goalsScored: 16,
      assists: 12,
      cleanSheets: 10,
      minutes: 2890,
      bonus: 30,
      bps: 620,
      creativity: 980.5,
      influence: 1122.4,
      threat: 901.7,
      ictIndex: 300.4,
      expectedGoals: 14.6,
      expectedAssists: 11.2,
      expectedGoalInvolvements: 25.8,
      expectedGoalsConceded: 22.3,
      cleanSheetsPer90: 0.31,
      starts: 33,
      tackles: 54,
      recoveries: 146,
      defensiveContribution: 88,
      status: "a",
    },
    history: [
      {
        element: 10,
        round: 1,
        totalPoints: 12,
        minutes: 90,
        goalsScored: 1,
        assists: 1,
        cleanSheets: 1,
        bonus: 3,
        bps: 42,
        creativity: 28.4,
        influence: 55.1,
        threat: 48.9,
        ictIndex: 13.2,
        expectedGoals: 0.64,
        expectedAssists: 0.31,
        expectedGoalInvolvements: 0.95,
        expectedGoalsConceded: 0.74,
        tackles: 4,
        recoveries: 8,
        clearancesBlocksInterceptions: 2,
        defensiveContribution: 5,
        starts: 1,
        opponentTeam: 2,
        value: 105,
        wasHome: true,
        kickoffTime: "2026-08-16T15:30:00Z",
      },
    ],
    upcomingFixtures: [],
  })),
}));

describe("App", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("renders the dashboard shell", async () => {
    render(<App />);
    expect(await screen.findByText(/Track form, fixtures, and gameweeks/i)).toBeInTheDocument();
    expect(await screen.findByRole("heading", { name: "Saka", level: 2 })).toBeInTheDocument();
    expect(await screen.findByText("xGI")).toBeInTheDocument();
  });
});
