import type {
  BootstrapResponse,
  ElementSummaryResponse,
  FixturesResponse,
} from "../src/client/fplApiClient.js";

export const bootstrapFixture: BootstrapResponse = {
  events: [
    {
      id: 1,
      name: "Gameweek 1",
      deadline_time: "2026-08-15T10:00:00Z",
      average_entry_score: 57,
      highest_score: 102,
      is_current: true,
      finished: false,
    },
  ],
  teams: [
    { id: 1, name: "Arsenal", short_name: "ARS", strength: 5 },
    { id: 2, name: "Chelsea", short_name: "CHE", strength: 4 },
    { id: 3, name: "Liverpool", short_name: "LIV", strength: 5 },
  ],
  element_types: [
    { id: 3, singular_name: "Midfielder", singular_name_short: "MID" },
  ],
  elements: [
    {
      id: 10,
      web_name: "Saka",
      first_name: "Bukayo",
      second_name: "Saka",
      team: 1,
      element_type: 3,
      now_cost: 105,
      total_points: 215,
      form: "7.8",
      selected_by_percent: "35.6",
      points_per_game: "6.1",
      goals_scored: 16,
      assists: 12,
      clean_sheets: 10,
      minutes: 2890,
      bonus: 30,
      bps: 620,
      creativity: "980.5",
      influence: "1122.4",
      threat: "901.7",
      ict_index: "300.4",
      expected_goals: "14.6",
      expected_assists: "11.2",
      expected_goal_involvements: "25.8",
      expected_goals_conceded: "22.3",
      clean_sheets_per_90: "0.31",
      starts: 33,
      tackles: 54,
      recoveries: 146,
      defensive_contribution: 88,
      status: "a",
    },
    {
      id: 11,
      web_name: "Salah",
      first_name: "Mohamed",
      second_name: "Salah",
      team: 3,
      element_type: 3,
      now_cost: 130,
      total_points: 260,
      form: "9.1",
      selected_by_percent: "45.1",
      points_per_game: "7.2",
      goals_scored: 22,
      assists: 14,
      clean_sheets: 11,
      minutes: 3000,
      bonus: 36,
      bps: 700,
      creativity: "1044.2",
      influence: "1305.6",
      threat: "1190.8",
      ict_index: "354.1",
      expected_goals: "20.5",
      expected_assists: "12.9",
      expected_goal_involvements: "33.4",
      expected_goals_conceded: "19.8",
      clean_sheets_per_90: "0.33",
      starts: 35,
      tackles: 38,
      recoveries: 121,
      defensive_contribution: 79,
      status: "a",
    },
    {
      id: 12,
      web_name: "Palmer",
      first_name: "Cole",
      second_name: "Palmer",
      team: 2,
      element_type: 3,
      now_cost: 109,
      total_points: 220,
      form: "8.4",
      selected_by_percent: "28.3",
      points_per_game: "6.5",
      goals_scored: 18,
      assists: 11,
      clean_sheets: 8,
      minutes: 2920,
      bonus: 28,
      bps: 641,
      creativity: "899.8",
      influence: "1188.2",
      threat: "1001.4",
      ict_index: "308.9",
      expected_goals: "16.8",
      expected_assists: "10.7",
      expected_goal_involvements: "27.5",
      expected_goals_conceded: "25.1",
      clean_sheets_per_90: "0.25",
      starts: 34,
      tackles: 47,
      recoveries: 132,
      defensive_contribution: 84,
      status: "a",
    },
  ],
};

export const fixturesFixture: FixturesResponse = [
  {
    id: 501,
    code: 111,
    event: 1,
    kickoff_time: "2026-08-16T15:30:00Z",
    team_h: 1,
    team_a: 2,
    team_h_score: null,
    team_a_score: null,
    finished: false,
    started: false,
  },
];

export function createElementSummaryFixture(playerId: number): ElementSummaryResponse {
  return {
    history: [
      {
        element: playerId,
        round: 1,
        total_points: 12,
        minutes: 90,
        goals_scored: 1,
        assists: 1,
        clean_sheets: 1,
        bonus: 3,
        bps: 42,
        creativity: "28.4",
        influence: "55.1",
        threat: "48.9",
        ict_index: "13.2",
        expected_goals: "0.64",
        expected_assists: "0.31",
        expected_goal_involvements: "0.95",
        expected_goals_conceded: "0.74",
        tackles: 4,
        recoveries: 8,
        clearances_blocks_interceptions: 2,
        defensive_contribution: 5,
        starts: 1,
        opponent_team: 2,
        value: 105,
        was_home: true,
        kickoff_time: "2026-08-16T15:30:00Z",
      },
      {
        element: playerId,
        round: 1,
        total_points: 7,
        minutes: 78,
        goals_scored: 1,
        assists: 0,
        clean_sheets: 0,
        bonus: 1,
        bps: 28,
        creativity: "14.2",
        influence: "39.5",
        threat: "35.8",
        ict_index: "8.9",
        expected_goals: "0.41",
        expected_assists: "0.06",
        expected_goal_involvements: "0.47",
        expected_goals_conceded: "1.11",
        tackles: 2,
        recoveries: 5,
        clearances_blocks_interceptions: 1,
        defensive_contribution: 3,
        starts: 1,
        opponent_team: 1,
        value: 105,
        was_home: false,
        kickoff_time: "2026-08-19T19:00:00Z",
      },
    ],
    fixtures: fixturesFixture.map((fixture) => ({
      id: fixture.id,
      code: fixture.code,
      event: fixture.event,
      kickoff_time: fixture.kickoff_time,
      team_h: fixture.team_h,
      team_a: fixture.team_a,
      team_h_score: fixture.team_h_score,
      team_a_score: fixture.team_a_score,
      finished: fixture.finished,
      started: fixture.started,
    })),
  };
}
